/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



package Interface;

<<<<<<< HEAD
import static Handler.DatosAcademicos.data;
import static Handler.DatosAcademicos.temp;
=======
>>>>>>> 3e382355926cf5bce371fde28d41ffe433d1116b
import Handler.Reservation;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Handler.Schedule;
<<<<<<< HEAD
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
=======
import java.time.format.DateTimeFormatter;
import static java.time.temporal.TemporalQueries.localTime;
import javax.swing.table.TableColumn;
>>>>>>> 3e382355926cf5bce371fde28d41ffe433d1116b

/**
 *
 * @author user
 */
public class Interface extends javax.swing.JFrame {

    Schedule schedule = new Schedule();
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        
        TableColumn firstColumn = table.getColumnModel().getColumn(0);
        firstColumn.setPreferredWidth(1);
        
    }

    public void showReserve(Reservation reservation) {
        DefaultTableModel modelo = (DefaultTableModel) table.getModel();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
        String horaBuscada = reservation.getBeginTime().format(formatter);

        String diaBuscado = reservation.getDay();
        Object nuevoValor = reservation.toString();
        
        for (int fila = 0; fila < modelo.getRowCount(); fila++) {
            for(int col = 0; col < modelo.getColumnCount(); col++) {
                
                String horaEnTabla = (String) modelo.getValueAt(fila, 0);
                String diaEnTabla = (String) modelo.getColumnName(col);
                if (horaEnTabla.equals(horaBuscada) && diaEnTabla.equals(diaBuscado)) {                    
                    modelo.setValueAt(nuevoValor, fila, col); 
                    modelo.fireTableDataChanged();
                    break;                         
               }
            }
        }        
    }
    
    /**
     * This method is called from within the
     * constructor to initialize the form.
     * WARNING: Do NOT modify this code. The
     * content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD
        Semestres = new javax.swing.JComboBox<>();
        ProyectoDeCarrera = new javax.swing.JComboBox<>();
=======
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
>>>>>>> 3e382355926cf5bce371fde28d41ffe433d1116b
        LapsoAcademico = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        Reservar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(80, 128, 128));

        Semestres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semestre 1", "Semestre 2", "Semestre 3", "Semestre 4" }));
        Semestres.setName("Semestres"); // NOI18N
        Semestres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemestresActionPerformed(evt);
            }
        });

        ProyectoDeCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proyecto de Carrera", "Administración De Empresas", "Administración Mención Banca Y Finanzas", "Ciencias Ambientales", "Ciencias FIscales", "Contaduría Pública", "Educación En Ciencias", "Educación Integral", "Educación. Mención Educación Física...", "Educación. Mención Lengua y Literatura...", "Educación. Mención Matemática", "Ingeniería En Informática", "Ingeniería En Materiales", "Ingeniería Industrial", "Licenciatura En Gestión De Alojamiento Turístico", "+ Añadir Proyecto de Carrera" }));
        ProyectoDeCarrera.setName("Semestres"); // NOI18N
        ProyectoDeCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProyectoDeCarreraActionPerformed(evt);
            }
        });

        LapsoAcademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lapso 2023-II", "+ Nuevo Lapso" }));
        LapsoAcademico.setName("Semestres"); // NOI18N
        LapsoAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapsoAcademicoActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "semana" }));
        jComboBox5.setName("Semestres"); // NOI18N
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sección 1", "+ Añadir Sección" }));
        jComboBox2.setName("Semestres"); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Filtrar Por");

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox1.setText("Aula");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox2.setText("Sede");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox3.setText("Cátedra");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox4.setText("Docente");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        Reservar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Reservar.setText("Reservar");
        Reservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservarMouseClicked(evt);
            }
        });
        Reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Horario");

        jButton2.setText("Iniciar Sesión");

        jScrollPane1.setBackground(new java.awt.Color(150, 245, 245));
        jScrollPane1.setToolTipText("");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"07:00", null, null, null, null, null},
                {"07:30", null, null, null, null, null},
                {"08:00", null, null, null, null, null},
                {"08:30", null, null, null, null, null},
                {"09:00", null, null, null, null, null},
                {"09:30", null, null, null, null, null},
                {"10:00", null, null, null, null, null},
                {"10:30", null, null, null, null, null},
                {"11:00", null, null, null, null, null},
                {"11:30", null, null, null, null, null},
                {"12:00", null, null, null, null, null},
                {"12:30", null, null, null, null, null},
                {"13:00", null, null, null, null, null},
                {"13:30", null, null, null, null, null},
                {"14:00", null, null, null, null, null},
                {"14:30", null, null, null, null, null},
                {"15:00", null, null, null, null, null},
                {"15:30", null, null, null, null, null},
                {"16:00", null, null, null, null, null},
                {"16:30", null, null, null, null, null},
                {"17:00", null, null, null, null, null},
                {"17:30", null, null, null, null, null}
            },
            new String [] {
                "Hora", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes"
            }
        ));
        table.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(table);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Exportar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Reservar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(137, 137, 137)
                        .addComponent(Semestres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(ProyectoDeCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(LapsoAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jButton2)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
                        .addContainerGap(51, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
<<<<<<< HEAD
                            .addComponent(Semestres, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProyectoDeCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
=======
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
>>>>>>> 3e382355926cf5bce371fde28d41ffe433d1116b
                            .addComponent(LapsoAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(Reservar)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addGap(28, 28, 28)
                        .addComponent(jButton3)
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SemestresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemestresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SemestresActionPerformed

    private void ProyectoDeCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProyectoDeCarreraActionPerformed
        
        String comparacion = null;
        String selectedProject = (String) ProyectoDeCarrera.getSelectedItem();
        
        for (Iterator<String> it = data.keySet().iterator(); it.hasNext();) {
            comparacion = it.next();
            if (comparacion.equals(selectedProject)){
                
            }
        }
        HashMap<String, ArrayList<String>> projectData = data.get(comparacion);
        Semestres.removeAllItems();
        for(String materia : projectData.keySet()){
            Semestres.addItem(materia);
        }
        
    }//GEN-LAST:event_ProyectoDeCarreraActionPerformed

    private void LapsoAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapsoAcademicoActionPerformed
        // TODO add your handling code here:
        String selection = (String) LapsoAcademico.getSelectedItem();
        
        if ("+ Nuevo Lapso".equals(selection)){
            
            int opcion = JOptionPane.showConfirmDialog(null, """
                                                             Esta acción eliminará todos los horarios almacenados del lapso actual para crear uno nuevo.
                                                             Estás seguro que quieres continuar?""","Confirmación", JOptionPane.YES_NO_OPTION);
            
            if (opcion == JOptionPane.YES_OPTION){
                
                DefaultComboBoxModel<String> modeloComboBox = (DefaultComboBoxModel<String>) jComboBox2.getModel();
                
                for(int i = 0; i < modeloComboBox.getSize();i++){
                   jComboBox2.removeItemAt(i);
                }
                
                String nuevaOpcion = "Lapso "+(JOptionPane.showInputDialog(this,"Ingrese el año y número del siguiente Lapso\n\"2023-I\", \"2024-II\" "));
            
            
                if (nuevaOpcion != null && !nuevaOpcion.isEmpty()){

<<<<<<< HEAD
=======
    private void LapsoAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapsoAcademicoActionPerformed
        // TODO add your handling code here:
        String selection = (String) LapsoAcademico.getSelectedItem();
        
        if ("+ Nuevo Lapso".equals(selection)){
            
            int opcion = JOptionPane.showConfirmDialog(null, """
                                                             Esta acción eliminará todos los horarios almacenados del lapso actual para crear uno nuevo.
                                                             Estás seguro que quieres continuar?""","Confirmación", JOptionPane.YES_NO_OPTION);
            
            if (opcion == JOptionPane.YES_OPTION){
                
                DefaultComboBoxModel<String> modeloComboBox = (DefaultComboBoxModel<String>) jComboBox2.getModel();
                
                for(int i = 0; i < modeloComboBox.getSize();i++){
                   jComboBox2.removeItemAt(i);
                }
                
                String nuevaOpcion = "Lapso "+(JOptionPane.showInputDialog(this,"Ingrese el año y número del siguiente Lapso\n\"2023-I\", \"2024-II\" "));
            
            
                if (nuevaOpcion != null && !nuevaOpcion.isEmpty()){

>>>>>>> 3e382355926cf5bce371fde28d41ffe433d1116b
                    String BorrarLapso = (String) LapsoAcademico.getItemAt(0);

                    LapsoAcademico.removeItem(BorrarLapso);

                    LapsoAcademico.insertItemAt(nuevaOpcion, 0);

                    LapsoAcademico.setSelectedItem(nuevaOpcion);

                }
            
            }else{
                
            }
        }
    }//GEN-LAST:event_LapsoAcademicoActionPerformed
    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed

    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void ReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarActionPerformed
        Reservation__Interface reservationFrame = new Reservation__Interface(this);
        reservationFrame.setVisible(true);
    }//GEN-LAST:event_ReservarActionPerformed

    private void ReservarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservarMouseClicked
    }//GEN-LAST:event_ReservarMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Codigo para tomar captura de pantalla al contenido del panel del Horario:
        try{
  
            //Calcula las dimensiones del panel
            int PanelWidth = jScrollPane1.getWidth();
            int PanelHeight = jScrollPane1.getHeight();        
            
            //Crea una imagen del mismo tamanio que el panel
            BufferedImage screenshot = new BufferedImage(PanelWidth, PanelHeight, BufferedImage.TYPE_INT_RGB);
            Graphics2D g2 = screenshot.createGraphics();
            
            // dibuja la tabla en la imagen y libera recursos
            jScrollPane1.print(g2);
            g2.dispose();
            
            //Generar un nombre unico basado en la fecha y la hora actual
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyMMdd_HHmmss");
            String timestamp = dateFormat.format(new Date());
            String filename = "Schedule" + timestamp + ".png";
            
            // Guarda la imagen en un archivo con el nombre generado
            File outputFile = new File(filename);
            ImageIO.write(screenshot, "png", outputFile);
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> LapsoAcademico;
<<<<<<< HEAD
    private javax.swing.JComboBox<String> ProyectoDeCarrera;
=======
>>>>>>> 3e382355926cf5bce371fde28d41ffe433d1116b
    private javax.swing.JButton Reservar;
    private javax.swing.JComboBox<String> Semestres;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox2;
<<<<<<< HEAD
=======
    private javax.swing.JComboBox<String> jComboBox3;
>>>>>>> 3e382355926cf5bce371fde28d41ffe433d1116b
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
